---
- name: Create folders
  become: no
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      recurse: yes
  with_items:
  - "{{ansible_user_dir}}/GitHub"
  - "{{ansible_user_dir}}/Bitbucket"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "git"
  - "subversion"
  - "mercurial"
  - "sshpass"
  - "curl"
  - "apt-transport-https"
  - "apache2-utils"
  - "httping"
  - "python-pip"
  - "python-dev"

- name: Install Python Packages
  become: yes
  pip:
      name: "{{item}}"
      state: latest
  with_items:
  - "pip"
  - "setuptools"
  - "httpie"

